### ISSUE TITLE
Split user and cluster configuration

### ISSUE THREAD

**Issue by schu** [kinvolk/kube-spawn#179]
Currently, kube-spawn uses a single configuration toml file for both user configuration (e.g. the k8s version to use) and node/cluster configuration (e.g. necessary bindmounts). This should be split.

**Comment by robertgzr** [comment]
This issue corresponds to the conversation we had [here](https://github.com/kinvolk/kube-spawn/pull/161#discussion_r146816040), right?

> Also we have the problem that not all of the options in the config file are possible to be set from env/cli (or make sense to be) - like the path mapping for example.
> This might be solvable by having two structures, one that viper binds to and the other we handle ourselves.

The initial problem was that we can't set path mappings via flags so the user has to edit kspawn.toml to mount additional files.

Why do you want to split it?
I think it's fine to expose those things, the problem is more how we handle the options from config/flags/evs internally.

**Comment by schu** [comment]
> This issue corresponds to https://github.com/kinvolk/kube-spawn/pull/161#discussion_r146816040

Yes.

> Why do you want to split it?

I would like to put configuration (e.g. k8s version to use, rktlet binary paths, ...) into configuration files and use those instead of long commands. Users then could also share kube-spawn config files where sensible.

**Comment by schu** [comment]
This is done as part of https://github.com/kinvolk/kube-spawn/pull/265
