### ISSUE TITLE
Using a "dev" hyperkube image doesn't seem to work correctly

### ISSUE THREAD

**Issue by schu** [kinvolk/kube-spawn#188]
When I use the `--dev` option, not all components seem to run from the provided hyperkube image. 

I have build version `1.8.2` and created a new cluster. While `kubectl get nodes` shows me version `1.8.2` for the nodes, `machinectl shell core@kubespawn0 /bin/bash -c 'kubectl version'` does return

```
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.2", GitCommit:"444a161d227565681bd2a475b4e654f4fda2b50f", GitTreeState:"clean", BuildDate:"2017-11-01T21:54:10Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

for the server.

**Comment by dongsupark** [comment]
In my case, on localhost I have a built k8s with version of `v1.9.0-alpha.1.967+bd5eeb10732529-dirty`, while the server version is `v1.9.0-alpha.2`.
```
$ /var/lib/kube-spawn/default/rootfs/usr/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.967+bd5eeb10732529-dirty", GitCommit:"bd5eeb107325293a8d9c9a952fffef77d1d3cad7", GitTreeState:"dirty", BuildDate:"2017-10-23T14:19:54Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.2", GitCommit:"444a161d227565681bd2a475b4e654f4fda2b50f", GitTreeState:"clean", BuildDate:"2017-11-01T21:54:10Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

The client version is obtained by the local build as expected, while the server version is determined by kubeadm, specifically `kubernetesVersion` in `kubeadm.yml`.

```
$ grep kubernetesVersion /var/lib/kube-spawn/default/rootfs/etc/kubeadm/kubeadm.yml
kubernetesVersion: latest
```

The version `latest` simply means the most recent version from the remote `k8s.io/kubernetes`, which is `v1.9.0-alpha.2`.

So far kube-spawn simply set `kubernetesVersion` to `latest` when `--dev` is specified, which is the reason for the mismatch. However, we cannot make the server version always the same as the client version, because kubeadm only supports either a released version or `latest`. For example, in my case above, I cannot use `v1.9.0-alpha.1.967+bd5eeb10732529-dirty` as the server version.

What we can do in practice is to gracefully figure out the most similar version. For example, from `v1.9.0-alpha.1.967+bd5eeb10732529-dirty` to `v1.9.0-alpha.1`, `v1.8.2+abcdefgh-dirty` to `v1.8.2`. Then we can set the converted valid version number to `kubeadm.yml`.

**Comment by alban** [comment]
During `kube-spawn start`, the function [distribution.PushImage()](https://github.com/kinvolk/kube-spawn/blob/a47b903/pkg/distribution/registry.go#L107-L110) tags `gcr.io/google-containers/hyperkube-amd64:latest` into `10.22.0.1:5000/hyperkube-amd64:latest`.

I think that the flag `kube-spawn --dev` should optionally accept a parameter to tag the image to the name of the cluster on the local insecure registry created by kube-spawn. In this way, we don't have to guess the "most similar version" and it will always work.

**Comment by alban** [comment]
kube-spawn calls kubeadm with the environment variable `KUBE_HYPERKUBE_IMAGE`.

[Documentation](https://kubernetes.io/docs/reference/generated/kubeadm/) says:
> Note: These environment variables are deprecated and will stop functioning in v1.8!

Kubernetes is now at `v1.10.0-alpha.0`, so the variable was ignored and it is picking the published hyperkube image instead of the locally build one.
